services:
  # MongoDB database
  mongo:
    image: mongo:8.0.4
    ports:
      - "27017:27017"
    networks:
      - passnest-network
    volumes:
      - passnest-mongo-data:/data/db

  # Node.js backend
  backend:
    image: aryanaroraa/passnest-backend:latest
    ports:
      - "3000:3000"
    networks:
      - passnest-network
    depends_on:
      - mongo

  # React frontend
  frontend:
    image: aryanaroraa/passnest-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - passnest-network
    depends_on:
      - backend

  # Nginx reverse proxy
  nginx-server:
    image: nginx
    networks:
      - passnest-network
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# Shared network for inter-container communication
networks:
  passnest-network:

# Persistent storage for MongoDB data
volumes:
  passnest-mongo-data: