services:
  mongo:
    image: mongo:8.0.4
    ports:
      - "27017:27017"
    networks:
      - passnest-network
    volumes:
      - passnest-mongo-data:/data/db
  
  backend:
    image: aryanaroraa/passnest-backend:latest
    ports:
      - "3000:3000"
    networks:
      - passnest-network
    depends_on:
      - mongo

  frontend:
    image: aryanaroraa/passnest-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - passnest-network
    depends_on:
      - backend
    
networks:
  passnest-network:

volumes:
  passnest-mongo-data: