# Workflow name
name: passnest pipeline

# Trigger pipeline on push to main branch
on:
  push:
    branches: ["main"]

jobs:
  build:
    # Use GitHub-hosted Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - uses: actions/checkout@v7

      # Set up Node.js
      - uses: actions/setup-node@v7
        with:
          node-version: 22

      # Install dependencies, lint and build frontend
      - name: Setting up npm for frontend
        run: |
          npm ci
          npm run lint
          npm run build

      # Install backend dependencies
      - name: Setting up npm for backend
        run: |
          cd backend
          npm ci

      # Build frontend Docker image
      - name: Building frontend docker image
        run: docker build -t aryanaroraa/passnest-frontend:latest .

      # Build backend Docker image
      - name: Building backend docker image
        run: docker build -t aryanaroraa/passnest-backend:latest ./backend

      # Authenticate with Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Push both images to Docker Hub
      - name: Pushing images to docker hub
        run: |
          docker push aryanaroraa/passnest-frontend:latest
          docker push aryanaroraa/passnest-backend:latest

      # Connect to EC2 and deploy the latest images
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd passnest-docker-cicd
            git pull origin main
            docker compose pull
            docker compose up -d --force-recreate