name: passnest pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Setting up npm 
        run: |
          npm ci
          npm run lint
          npm run build
        
      - name: Building frontend docker image
        run: docker build -t aryanaroraa/passnest-frontend:latest .
        
      - name: Building backend docker image
        run: docker build -t aryanaroraa/passnest-backend:latest ./backend
